### ISSUE TITLE
Turn the standard app title bar into the search bar

### ISSUE THREAD

**Issue by VBeegle** [MobileApps-Cascadia/orca-stars-android#30]
Def: Troubleshoot how to turn the app title bar into the search bar from the Digital Prototype.

DoD: Understand how to change the app title bar into the search bar.

**Comment by Bansenauer-Cascadia** [comment]
I'm  confused by this issue being closed since a search bar is NOT implemented in the title bar on the develop branch. Please provide more comments here to document if the team decided to change this issue.

**Comment by JoshuaAaron** [comment]
After team discussion over the client's feedback, we decided to go a different direction. The search bar was taken in out in favor of a category search through the home screen icons. The code has been commented out for the time being.
