### ISSUE TITLE
Figure out how to create rounded corners for a image button

### ISSUE THREAD

**Issue by VBeegle** [MobileApps-Cascadia/orca-stars-android#31]
Def: Understand how to create rounded corners for an image button's image and implement.

DoD: Added rounded corners to image buttons

**Comment by JoshuaAaron** [comment]
https://stackoverflow.com/questions/9334618/rounded-button-in-android

and 

https://medium.com/@inibukanadit/androidstarter-1-i-want-a-round-button-636bc5553d6d

are 2 good resources on rounded buttons.
