### ISSUE TITLE
Add About Feature to Bottom Toolbar Info Button

### ISSUE THREAD

**Issue by JoshuaAaron** [MobileApps-Cascadia/orca-stars-android#55]
Def: Add an activity or fragment that gets created when the user clicks the info button on the bottom toolbar.

DoD: The info button correctly displays the about activity that contains information about the Orca Conservancy and OrcaStars, when the user presses the "i" icon on the bottom toolbar.

**Comment by charlesmsy** [comment]
Notes: This contains both about sections in this issue card.

**Comment by JoshuaAaron** [comment]
#complete
I've successfully added the "About Us" fragment that gets created when the user clicks the info button on the bottom toolbar.
The DoD was that the info button correctly displays the about activity that contains information about the Orca Conservancy and OrcaStars, when the user presses the "i" icon on the bottom toolbar. For the most part, what has been done follows the DoD, but I still need to add the logo and about blurb. I will be working on that tomorrow. I would say that this issue isn't technically complete, but I could also make the case that I can create a new issue to address that in the next sprint.
