### ISSUE TITLE
"More" Menu

### ISSUE THREAD

**Issue by charlesmsy** [MobileApps-Cascadia/orca-stars-android#57]
Def: The more button brings up a category menu. Buttons/ items do not need to be functional at this point.

DoD: Category menu able to display 10-15 categories on the main activity using fragments.

**Comment by VBeegle** [comment]
https://www.materialpalette.com/icons

**Comment by charlesmsy** [comment]
Pilot data 

https://docs.google.com/spreadsheets/d/1ADI3Td1njnG67kMIvPaP7K6crpgkFGqQLEqot45-ukc/edit#gid=0
