### ISSUE TITLE
Business List Adapter

### ISSUE THREAD

**Issue by VBeegle** [MobileApps-Cascadia/orca-stars-android#71]
FOLDERS: Other:* ViewModel:** Model:*** DB:**** UI:*****
Def: Create/update BusinessLogoAdapter -> BusinessLIstAdapter***** Create BusinessMoreAdaptor*****
Copy BusinessLogoAdapter and rename it to BusinessMoreAdapter. Leave it to work with the More Menu. Turn the copy into the BusinessListAdapter.
Ref: https://github.com/android/architecture-components-samples/tree/master/BasicSample/app/src/main/java/com/example/android/persistence 
DoD: Create/update files to complete Business(3/3)

**Comment by charlesmsy** [comment]
Completion notes:
This issue is tied with issue #73 (see card #73 73). This does meet Dod, but has not been pushed to develop branch.
