### ISSUE TITLE
BusinessList

### ISSUE THREAD

**Issue by VBeegle** [MobileApps-Cascadia/orca-stars-android#73]
FOLDERS: Other:* ViewModel:** Model:*** DB:**** UI:*****
Def: Create/update BusinessListFragment*****, BusinessListViewModel** Reference ProductListFragment and ProductListViewModel. Update fragment_restaurant_menu.xml and rename it to fragment_business_list.xml
Turn RestaurantMenuFragment into BusinessListFragment.
Ref: https://github.com/android/architecture-components-samples/tree/master/BasicSample/app/src/main/java/com/example/android/persistence 
DoD: Create/update files to complete Business(1/3)

**Comment by charlesmsy** [comment]
Completion notes:
Does meet the DoD, but has not been pushed to develop. Major changes have been made to the app. Redone architecture of the app. XML file heavily changed to resolve conflict issues. App can not be built, has binding issues that need to be resolved prior to the merge with develop branch.

Card #73 is tied to card #71 and #72 (meaning this issue has the codes for 71 and 72)
